### ISSUE TITLE
App crashes after headphones plugged in

### ISSUE THREAD

**Issue by Solitary** [vanilla-music/vanilla-headphone-detector#20]
Hi, recently I noticed that the app stopped working (Vanilla Music doesn't start to play after headphones connected) and whenever they are connected the app instantly crashes after it is opened. It might have happened since recent Vanilla Music update, but unsure as I wasn't paying close attention at the time and some time passed since noticing till I got to analyze the issue.

I noticed in log this error, but can provide more as I am unsure what is exactly relevant or not:
```FATAL EXCEPTION: main
Process: ch.blinkenlights.android.vanillaplug, PID: 14403
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.HEADSET_PLUG flg=0x40000010 (has extras) } in ch.blinkenlights.android.vanillaplug.VPlugService$1@8173e8a
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1816)
	at android.app.LoadedApk$ReceiverDispatcher$Args$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=ch.blinkenlights.android.vanilla.action.PLAY flg=0x10000000 cmp=ch.blinkenlights.android.vanilla/.PlaybackService } without permission not exported from uid 10252
	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1935)
	at android.app.ContextImpl.startForegroundService(ContextImpl.java:1893)
	at android.content.ContextWrapper.startForegroundService(ContextWrapper.java:798)
	at ch.blinkenlights.android.vanillaplug.VPlugService$1.onReceive(VPlugService.java:101)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1806)
	... 9 more
```

This happens on my Samsung Galaxy S10+ (Android 12) (output is from that), and similar behavior on S22+ (Android 13, using dongle).

VanillaMusic installed through Google Play in version 1.2.2, Headphone detector in version 1.7 also from Play.

**Comment by robinpaulson** [comment]
Yeah it's not working here either. I upgraded vanilla in January, installed the headphone plugin for the first time soon after. Both installed from fdroid. I'm on lineage 16, Samsung s5 mini.

**Comment by klaufir216** [comment]
Currently downgrading to Vanilla Music 1.1.0 in F-Droid works as a temporary solution.

**Comment by klaufir216** [comment]
The key is this from the log:

```
Caused by: java.lang.SecurityException: Not allowed to start service Intent { act=ch.blinkenlights.android.vanilla.action.PLAY flg=0x10000000
cmp=ch.blinkenlights.android.vanilla/.PlaybackService } without permission not exported from uid 10252
```

So the headphone detector has no permission to start the ch.blinkenlights.android.vanilla.action.PLAY intent in Vanilla Music.


The problem is in the manifest of Vanilla Music:
```
		<service android:name="PlaybackService"
			 android:foregroundServiceType="mediaPlayback"
			 android:exported="false">
			<intent-filter>
				<action android:name="ch.blinkenlights.android.vanilla.action.PLAY" />
				<action android:name="ch.blinkenlights.android.vanilla.action.PAUSE" />
				<action android:name="ch.blinkenlights.android.vanilla.action.TOGGLE_PLAYBACK" />
				<action android:name="ch.blinkenlights.android.vanilla.action.NEXT_SONG" />
				<action android:name="ch.blinkenlights.android.vanilla.action.PREVIOUS_SONG" />
			</intent-filter>
		</service>
```

Here

```
android:exported="false"
```

should have been

```
android:exported="true"
```

**Comment by Antimailer** [comment]
Hi, is there any chance of rolling out a version vanilla 1.3.1 in the next few days/weeks (especially on f-droid) because the vanilla app crashes are very impactful. Thanks in advance.

**Comment by robinpaulson** [comment]
@Antimailer yes, this would be much appreciated

**Comment by Antimailer** [comment]
Thanks for the commit. But how we get the new version 1.3.1 on F-Droid (there is still 1.3.0)
